"""ISG WPM G entities from chapter 9; see docs/wpmg-register-coverage.md."""

from collections.abc import Callable
from typing import Any, cast


def wpmg_accessor(
    component: str, attribute: str
) -> Callable[[Any], int | float | None]:
    """Bind a catalog entry to its typed library component."""

    def read(api: Any) -> int | float | None:
        return cast(int | float | None, getattr(getattr(api, component), attribute))

    return read


WPMG_MEASUREMENTS = (
    ("system_values", "buffer_cylinder_temperature", "°C"),
    ("system_values", "heating_circuit_1_flow_temperature", "°C"),
    ("system_values", "heating_circuit_2_flow_temperature", "°C"),
    ("system_values", "heating_circuit_3_flow_temperature", "°C"),
    ("system_values", "heating_circuit_4_flow_temperature", "°C"),
    ("system_values", "heating_circuit_5_flow_temperature", "°C"),
    ("system_values", "heating_circuit_2_return_temperature", "°C"),
    ("system_values", "heating_circuit_3_return_temperature", "°C"),
    ("system_values", "heating_circuit_4_return_temperature", "°C"),
    ("system_values", "heating_circuit_5_return_temperature", "°C"),
    ("system_values", "cooling_circuit_return_temperature", "°C"),
    ("system_values", "cooling_cylinder_temperature", "°C"),
    ("system_values", "cooling_cylinder_return_temperature", "°C"),
    ("system_values", "cooling_cylinder_flow_temperature", "°C"),
    ("system_values", "dhw_draw_off_control_flow_temperature", "°C"),
    ("system_values", "dhw_draw_off_control_return_temperature", "°C"),
    ("system_values", "dhw_charging_system_return_temperature", "°C"),
    ("system_values", "dhw_draw_off_control_cylinder_temperature", "°C"),
    ("system_values", "system_sensor_upper_dhw_temperature", "°C"),
    ("system_values", "system_sensor_lower_dhw_temperature", "°C"),
    ("system_values", "brine_inlet_temperature", "°C"),
    ("system_values", "brine_outlet_temperature", "°C"),
    ("system_values", "hot_gas_temperature", "°C"),
    ("system_values", "condenser_inlet_temperature", "°C"),
    ("system_values", "condenser_outlet_temperature", "°C"),
    ("system_values", "liquid_line_temperature", "°C"),
    ("system_values", "suction_gas_temperature", "°C"),
    ("system_values", "pool_flow_temperature", "°C"),
    ("system_values", "pool_return_temperature", "°C"),
    ("system_values", "hot_gas_mode_dhw_flow_temperature", "°C"),
    ("system_values", "outside_temperature_averaged", "°C"),
    ("system_values", "dhw_temperature_weighted", "°C"),
    ("system_values", "evaporation_temperature_in_high_pressure_range", "°C"),
    ("system_values", "condensation_temperature_in_high_pressure_range", "°C"),
    ("system_values", "condensation_temperature_in_low_pressure_range", "°C"),
    ("system_values", "superheating", "K"),
    ("system_values", "supercooling", "K"),
    ("system_values", "pressure_low_pressure_side", "bar"),
    ("system_values", "pressure_high_pressure_side", "bar"),
    ("system_values", "l1_current", "A"),
    ("system_values", "l2_current", "A"),
    ("system_values", "l3_current", "A"),
    ("system_values", "l1_n_voltage", "V"),
    ("system_values", "l2_n_voltage", "V"),
    ("system_values", "l3_n_voltage", "V"),
    ("system_values", "l1_l2_voltage", "V"),
    ("system_values", "l2_l3_voltage", "V"),
    ("system_values", "l3_l1_voltage", "V"),
    ("system_values", "l1_power_consumption", "W"),
    ("system_values", "l2_power_consumption", "W"),
    ("system_values", "l3_power_consumption", "W"),
    ("system_values", "set_buffer_cylinder_temperature", "°C"),
    ("system_values", "current_output_stage_compressor", ""),
    ("system_values", "current_output_stage_internal_booster_heater", ""),
    ("system_values", "percentage_compressor_speed", "%"),
)

WPMG_STATUSES = (
    ("system_values", "sg_ready_input_1"),
    ("system_values", "sg_ready_input_2"),
    ("system_values", "external_stop_pool_heating"),
    ("system_values", "external_start_brine_pump"),
    ("system_values", "start_delay_active"),
    ("system_state", "control_signal_external_booster_heater"),
    ("system_state", "control_signal_internal_booster_heater_stage_2"),
    ("system_state", "control_signal_heating_circuit_1_circulation_pump"),
    ("system_state", "control_signal_condenser"),
    ("system_state", "control_signal_internal_booster_heater_stage_1"),
    ("system_state", "control_signal_hot_gas_circulation_pump"),
    ("system_state", "control_signal_brine_pump"),
    ("system_state", "control_signal_external_booster_heater_dhw_circulation_pump"),
    ("system_state", "control_signal_external_relay_for_brine_pump"),
    ("system_state", "feedback_external_booster_heater"),
    ("system_state", "feedback_internal_booster_heater"),
    ("system_state", "control_signal_hot_gas_control"),
    ("system_state", "heat_pump_off"),
    ("system_state", "heat_pump_ready_to_start"),
    ("system_state", "control_signal_dhw_draw_off_control_flow_dhw_circulation_pump"),
    ("system_state", "control_signal_dhw_charging_system_control"),
    ("system_state", "control_signal_dhw_charging_system_dhw_circulation_pump"),
    ("system_state", "control_signal_dhw_draw_off_control_cylinder_heating"),
    ("system_state", "control_signal_cooling_circuit_dhw_circulation_pump"),
    ("system_state", "control_signal_pool_dhw_circulation_pump"),
    ("system_state", "control_signal_cooling_circuit_control"),
    ("system_state", "control_signal_pool_control"),
    ("system_state", "note_if_mixing_valve_used_for_passive_cooling"),
    ("system_state", "control_signal_compressor"),
    ("system_state", "compressor_cannot_start"),
    ("alarms", "level_1_notification"),
    ("alarms", "level_2_notification"),
    ("alarms", "level_3_notification"),
    ("alarms", "level_1_notification_high_pressure"),
    ("alarms", "level_1_notification_low_pressure"),
    ("alarms", "level_1_notification_hot_gas_temperature"),
    ("alarms", "level_1_notification_operating_pressure"),
    ("alarms", "level_1_notification_hot_gas_line_sensor"),
    ("alarms", "level_1_notification_liquid_line_sensor"),
    ("alarms", "level_1_notification_suction_gas_sensor"),
    ("alarms", "level_1_notification_flow_rate_pressure_brine_or_condenser"),
    ("alarms", "level_1_notification_bm_card_phase_sequence"),
    ("alarms", "level_1_notification_inverter_fault"),
    ("alarms", "level_3_notification_low_source_temperature"),
    ("alarms", "level_1_notification_low_compressor_speed"),
    ("alarms", "level_1_notification_low_superheating"),
    ("alarms", "level_1_notification_outside_pressure_ratio"),
    ("alarms", "level_1_notification_outside_operating_range"),
    ("alarms", "level_1_notification_brine_temperature_outside_range"),
    ("alarms", "level_2_notification_brine_inlet_sensor"),
    ("alarms", "level_2_notification_brine_outlet_sensor"),
    ("alarms", "level_2_notification_condenser_inlet_sensor"),
    ("alarms", "level_2_notification_condenser_outlet_sensor"),
    ("alarms", "level_2_notification_outside_temperature_sensor"),
    ("alarms", "level_2_notification_system_flow_sensor"),
    ("alarms", "level_2_notification_heating_circuit_1_sensor"),
    ("alarms", "level_2_notification_heating_circuit_2_sensor"),
    ("alarms", "level_2_notification_heating_circuit_3_sensor"),
    ("alarms", "level_2_notification_heating_circuit_4_sensor"),
    ("alarms", "level_2_notification_heating_circuit_5_sensor"),
    ("alarms", "level_2_notification_dhw_charging_circuit_sensor"),
    ("alarms", "level_2_notification_dhw_sensor"),
    ("alarms", "level_2_notification_cooling_buffer_sensor"),
    ("alarms", "level_2_notification_cooling_cylinder_flow_sensor"),
    ("alarms", "level_2_notification_cooling_circuit_return_sensor"),
    ("alarms", "level_2_notification_source_circuit_spread_max"),
    ("alarms", "level_2_notification_dhw_centre_sensor"),
    ("alarms", "level_2_notification_dhw_return_sensor"),
    ("alarms", "level_2_notification_dhw_hot_gas_sensor"),
    ("alarms", "level_2_notification_internal_booster_heater"),
    ("alarms", "level_3_notification_condenser_maximum_temperature"),
    ("alarms", "level_2_notification_max_brine_inlet"),
    ("alarms", "level_2_notification_min_brine_inlet"),
    ("alarms", "level_2_notification_min_brine_outlet"),
    ("alarms", "level_3_notification_min_dhw_circulation_return"),
    ("alarms", "level_3_notification_min_dhw_circulation_temperature"),
    ("alarms", "level_3_notification_heating_circuit_1_temperature"),
    ("alarms", "level_3_notification_heating_circuit_2_temperature"),
    ("alarms", "level_3_notification_heating_circuit_3_temperature"),
    ("alarms", "level_3_notification_heating_circuit_4_temperature"),
    ("alarms", "level_3_notification_heating_circuit_5_temperature"),
    ("alarms", "level_3_notification_dhw_circulation_return_temperature"),
    ("alarms", "notification_central_message"),
    ("alarms", "level_3_notification_cooling_circuit_temperature"),
    ("alarms", "level_3_notification_cooling_buffer_temperature"),
    ("alarms", "level_2_notification_humidity_sensor"),
    ("alarms", "level_2_notification_cooling_buffer_return_sensor"),
    ("alarms", "level_3_notification_room_temperature_sensor"),
    ("alarms", "level_1_notification_inverter_communication"),
    ("alarms", "level_2_notification_pool_return_sensor"),
    ("alarms", "level_2_notification_cooling_heating_circuit_1_sensor"),
    ("alarms", "level_2_notification_dhw_cylinder_sensor"),
    ("alarms", "level_2_notification_maximum_pasteurisation_time"),
    ("alarms", "level_3_notification_external_alarm"),
)
